config/routes.rb
Rails.application.routes.draw do

  resources :interventions do
    get :get_buildings_for_customer, on: :collection
    get :get_batteries_for_building, on: :collection
    get :get_columns_for_battery, on: :collection
    get :get_elevators_for_column, on: :collection
  end
  # resources :interventions
  resources :leads
  devise_for :users
  resources :quotes
  get 'website/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'website#index'
  
  get '/index', to: 'website#index'
  
  get '/residential', to: 'website#residential'

  get '/commercial', to: 'website#commercial'

  get '/quote', to: 'website#quote'

  get '/google', to: 'google#maps'

  post '/watson/greetings', to: 'watson#greetings'

end

app/models/quote.rb
class Quote < ApplicationRecord
    # after_create :ticket_create_quote
    # require 'zendesk_api'

    # def ticket_create_quote
    #     client = ZendeskAPI::Client.new do |config|
    #         # Mandatory:
          
    #         config.url = "https://rocketelevator8148.zendesk.com/api/v2" # e.g. https://rocketelevator8148.zendesk.com/api/v2
          
    #         # Basic / Token Authentication
    #         config.username = "rocketelevator@hotmail.com"
            
          
    #         # Choose one of the following depending on your authentication choice
    #         config.token = ENV["ZENDESK_APIKEY"]
          
    #       #   # OAuth Authentication
    #       #   config.access_token = "your OAuth access token"
          
    #         # Optional:
          
    #         # Retry uses middleware to notify the user
    #         # when hitting the rate limit, sleep automatically,
    #         # then retry the request.
    #         config.retry = true
          
    #         # Raise error when hitting the rate limit.
    #         # This is ignored and always set to false when `retry` is enabled.
    #         # Disabled by default.
    #         config.raise_error_when_rate_limited = false
          
    #         # Logger prints to STDERR by default, to e.g. print to stdout:
    #         require 'logger'
    #         config.logger = Logger.new(STDOUT)
          
    #         # Disable resource cache (this is enabled by default)
    #         config.use_resource_cache = false
          
    #         # Changes Faraday adapter
    #         # config.adapter = :patron
          
    #         # Merged with the default client options hash
    #         # config.client_options = {:ssl => {:verify => false}, :request => {:timeout => 30}}
          
    #         # When getting the error 'hostname does not match the server certificate'
    #         # use the API at https://yoursubdomain.zendesk.com/api/v2
    #     end
    #     # ticket = ZendeskAPI::Ticket.new("#{client}", :id => 1, :priority => "urgent")
    #     puts "This is the client after creation #{client}"
    #     client.tickets.create(:subject => "#{company_name} at #{email}", 
    #         :comment => { :value => "The company #{company_name} which can be reached at email #{email} sent us a quote requesting Rocket Elevators services. Here's the key elements of the quote we received:
    #         Building type: #{name}
    #         Product Line Quality: #{product_line}
    #         Number of Apartments: #{number_of_appartement}
    #         Number of Floors: #{number_of_floor}
    #         Number of Basements: #{number_of_basement}
    #         Number of Companies: #{number_of_companies}
    #         Number of Parking Spots: #{number_of_parking_spots}
    #         Number of Corporations: #{number_of_corporations}
    #         Maximum Occupancy: #{maximum_occupancy}
    #         Total Business Hours/Day: #{business_hours}
    #         Amount of Elevator needed: #{number_of_elevators}
    #         Unit Price per Elevator: #{unit_price_of_each_elevator}
    #         Total Price of All Elevators: #{total_price_of_elevators}
    #         Installation fees: #{installation_fees}
    #         Total Price: #{final_price}" }, 
    #         :submitter_id => client.current_user.id, 
    #         :type => "task",
    #         :priority => "normal")
    #     puts "Ticket creation?"
    #     client.tickets.save
    #     puts "Ticket saved?"
    # end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to index_url, notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quotes).permit(:name, :product_line, :number_of_appartement, :number_of_floor, :number_of_basement, :number_of_companies, :number_of_parking_spots, :number_of_elevators, :number_of_corporations, :maximum_occupancy, :business_hours, :unit_price_of_each_elevator, :total_price_of_elevators, :installation_fees, :final_price, :company_name, :email)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :product_line %>
    <%= form.text_field :product_line %>
  </div>

  <div class="field">
    <%= form.label :number_of_elevator %>
    <%= form.text_field :number_of_elevator %>
  </div>

  <div class="field">
    <%= form.label :unit_price_of_each_elevator %>
    <%= form.text_field :unit_price_of_each_elevator %>
  </div>

  <div class="field">
    <%= form.label :total_price_of_elevators %>
    <%= form.text_field :total_price_of_elevators %>
  </div>

  <div class="field">
    <%= form.label :installation_fees %>
    <%= form.text_field :installation_fees %>
  </div>

  <div class="field">
    <%= form.label :final_price %>
    <%= form.text_field :final_price %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product line</th>
      <th>Number of elevator</th>
      <th>Unit price of each elevator</th>
      <th>Total price of elevators</th>
      <th>Installation fees</th>
      <th>Final price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.name %></td>
        <td><%= quote.product_line %></td>
        <td><%= quote.number_of_elevator %></td>
        <td><%= quote.unit_price_of_each_elevator %></td>
        <td><%= quote.total_price_of_elevators %></td>
        <td><%= quote.installation_fees %></td>
        <td><%= quote.final_price %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @quote.name %>
</p>

<p>
  <strong>Product line:</strong>
  <%= @quote.product_line %>
</p>

<p>
  <strong>Number of appartement:</strong>
  <%= @quote.number_of_appartement %>
</p>

<p>
  <strong>Number of floors:</strong>
  <%= @quote.number_of_floor %>
</p>

<p>
  <strong>Number of basements:</strong>
  <%= @quote.number_of_basement %>
</p>

<p>
  <strong>Number of companies:</strong>
  <%= @quote.number_of_companies %>
</p>

<p>
  <strong>Number of parking spots:</strong>
  <%= @quote.number_of_parking_spots %>
</p>


<p>
  <strong>Number of elevator:</strong>
  <%= @quote.number_of_elevators %>
</p>

<p>
  <strong>Number of corporations:</strong>
  <%= @quote.number_of_corporations %>
</p>

<p>
  <strong>Maximum occupancy:</strong>
  <%= @quote.maximum_occupancy %>
</p>

<p>
  <strong>Business hours:</strong>
  <%= @quote.business_hours %>
</p>

<p>
  <strong>Unit price of each elevator:</strong>
  <%= @quote.unit_price_of_each_elevator %>
</p>

<p>
  <strong>Total price of elevators:</strong>
  <%= @quote.total_price_of_elevators %>
</p>

<p>
  <strong>Installation fees:</strong>
  <%= @quote.installation_fees %>
</p>

<p>
  <strong>Final price:</strong>
  <%= @quote.final_price %>
</p>

<p>
  <strong>Company Name:</strong>
  <%= @quote.company_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @quote.email %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>