config/routes.rb
Rails.application.routes.draw do

  resources :interventions do
    get :get_buildings_for_customer, on: :collection
    get :get_batteries_for_building, on: :collection
    get :get_columns_for_battery, on: :collection
    get :get_elevators_for_column, on: :collection
  end
  # resources :interventions
  resources :leads
  devise_for :users
  resources :quotes
  get 'website/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'website#index'
  
  get '/index', to: 'website#index'
  
  get '/residential', to: 'website#residential'

  get '/commercial', to: 'website#commercial'

  get '/quote', to: 'website#quote'

  get '/google', to: 'google#maps'

  post '/watson/greetings', to: 'watson#greetings'

end

app/models/intervention.rb
class Intervention < ApplicationRecord 
    validates :author_id, presence: true
    validates :customer_id, presence: true
    validates :building_id, presence: true
    validate :intervention_valid

    belongs_to :author, class_name: "Employee"
    belongs_to :employee, class_name: "Employee", optional: true
    belongs_to :customer, class_name: "Customer"
    belongs_to :building, class_name: "Building"
    belongs_to :battery, class_name: "Battery", optional: true
    belongs_to :column, class_name: "Column", optional: true
    belongs_to :elevator, class_name: "Elevator", optional: true


    def intervention_valid
        if !self.customer_id && !self.building_id
            errors.add(:you, 'must select at least one of the following option: Battery, Column, Elevator')
        end

    end



       after_create :ticket_create_contact
    require 'zendesk_api'

    def ticket_create_contact
        client = ZendeskAPI::Client.new do |config|
            # Mandatory:
          
            config.url = "https://abdelhakim.zendesk.com/api/v2" # e.g. https://rocketelevator8148.zendesk.com/api/v2
          
            # Basic / Token Authentication
            config.username = "hakimososos@gmail.com"
            
          
            # Choose one of the following depending on your authentication choice
            config.token = ENV["ZENDESK_APIKEY"]
          
          #   # OAuth Authentication
          #   config.access_token = "your OAuth access token"
          
            # Optional:
          
            # Retry uses middleware to notify the user
            # when hitting the rate limit, sleep automatically,
            # then retry the request.
            config.retry = true
          
            # Raise error when hitting the rate limit.
            # This is ignored and always set to false when `retry` is enabled.
            # Disabled by default.
            config.raise_error_when_rate_limited = false
          
            # Logger prints to STDERR by default, to e.g. print to stdout:
            require 'logger'
            config.logger = Logger.new(STDOUT)
          
            # Disable resource cache (this is enabled by default)
            config.use_resource_cache = false
          
            # Changes Faraday adapter
            # config.adapter = :patron
          
            # Merged with the default client options hash
            # config.client_options = {:ssl => {:verify => false}, :request => {:timeout => 30}}
          
            # When getting the error 'hostname does not match the server certificate'
            # use the API at https://yoursubdomain.zendesk.com/api/v2
        end
        # ticket = ZendeskAPI::Ticket.new("#{client}", :id => 1, :priority => "urgent")
        customer = Customer.find(customer_id)
        author = Employee.find(author_id)
        employee = Employee.find(employee_id)
        intervention = Intervention.find(id)

        puts "This is the client after creation #{intervention.id}"
        client.tickets.create(
            :subject => "Intervention #{intervention.id}", 
            :comment => { :value => "The author #{author.first_name} #{author.last_name} created a ticket for the company #{customer.compagny_name} for the Building ID: #{building_id}, Battery ID: #{battery_id}, Column ID: #{column_id}, Elevator ID: #{elevator_id}. The employee assigned to this task is #{employee.first_name} #{employee.last_name}" }, 
            :submitter_id => client.current_user.id,
            :type => "question", 
            :priority => "normal")
        puts "Ticket creation?"
        client.tickets.save
        puts "Ticket saved?"
    end
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]
  before_action :has_access

  # GET /interventions or /interventions.json
  def index
    redirect_to index_url
    @interventions = Intervention.all
  end

  def has_access
    if current_user
      if current_user.employee || current_user.is_admin
      else
        respond_to do |format|
          format.html { redirect_to root_path, notice: "You need to be an Employee to access in this page" }
        end 
      end
    else
      respond_to do |format|
        format.html { redirect_to (root_path + 'users/sign_in'), notice: "You need to be an Employee to access in this page" }
      end
    end
  end

 
  # GET /interventions/1 or /interventions/1.json
  def show
    redirect_to index_url
  end

  # GET /interventions/new
  def new
    redirect_to index_url
    @intervention = Intervention.new
  end

  # GET /interventions/1/edit
  def edit
    redirect_to index_url
  end

  # POST /interventions or /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)

    if current_user.employee
      @intervention.author_id = Employee.where(user_id: current_user.id)[0].id
    end

    @intervention.result = 'Incomplete'
    @intervention.status = 'Pending'
    @intervention.start_date = 'null'
    @intervention.end_date = 'null'
    @intervention.employee_id
    @intervention.valid?
  

    @intervention.save
    respond_to do |format|
      if @intervention.save
        format.html { redirect_to @intervention, notice: "Intervention was successfully created." }
        format.json { render :show, status: :created, location: @intervention }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # def get_buildings_for_customer
  #   puts "get_buildings_for_customer"
  #   puts params
  #   # @buildings = Customer.find(params[:])
  #   @buildings = Building.where("customer_id = ?", params[:customerid])
  #   puts "here are the buildings:"
  #   puts @buildings
  #   respond_to do |format|
  #   format.json { render :json => @buildings }
  #   end
  # end

  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update

    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to @intervention, notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_buildings_for_customer
    puts "get_buildings_for_customer"
    puts params
    @buildings = Building.where("customer_id = ?", params[:customer_id])
    puts "here are the buildings:"
    puts @buildings
    respond_to do |format|
    format.json { render :json => @buildings }
    end
  end

  def get_batteries_for_building
    puts "get_batteries_for_building"
    puts params
    @batteries = Battery.where("building_id = ?", params[:building_id])
    puts "here are the batteries:"
    puts @batteries
    respond_to do |format|
    format.json { render :json => @batteries }
    end
  end

  def get_columns_for_battery
    puts "get_columns_for_battery"
    puts params
    @columns = Column.where("battery_id = ?", params[:battery_id])
    respond_to do |format|
    format.json { render :json => @columns }
    end
  end

  def get_elevators_for_column
    puts "get_elevators_for_column"
    puts params
    @elevators = Elevator.where("column_id = ?", params[:column_id])
    respond_to do |format|
    format.json { render :json => @elevators }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:author_id, :customer_id, :building_id, :battery_id, :column_id, :elevator_id, :employee_id, :start_date, :end_date, :result, :report, :status)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<div id="header" class="navbar-toggleable-md sticky clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">

						<!-- Mobile Menu Button -->
						<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars"></i>
						</button>

						<!-- Logo -->
						<a class="logo float-left scrollTo" href="#top" style="background-color: #FFFFFF">
							<img src="<%= asset_path('R2.png') %>" alt="" />
						</a>

						<!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
						<div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
							<nav class="nav-main">

								<!-- 
									
									
									Add .external for an external link!
								-->
								<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
									<li class="active"><!-- HOME -->
										<a id="home-nav" href="/index">
											HOME
										</a>
									</li>
									<li><!-- SERVICES -->
										<li class="dropdown">
										<a class="dropdown-toggle" id="services-nav" href="/index#services">
										  SERVICES
											</a>
										<ul class="dropdown-menu">
										  <li><a href="residential">Residential</a></li>
										  <li><a href="commercial">Commercial</a></li>
										</ul>
									</li>
									</li>
									<li><!-- PORTFOLIO -->
										<a id="portfolio-nav" href="/index#PORTFOLIO">
											PORTFOLIO
										</a>
									</li>
									<li><!-- NEWS -->
										<a id="news-nav" href="/index#news">
											NEWS
										</a>
									</li>

									<li><!-- CLIENTS -->
										<a id="clients-nav" href="/index#clients">
											CLIENTS
										</a>
									</li>

									<li><!-- CONTACT -->
										<a id="contact-nav" href="/index#contact">
											CONTACT
										</a>
									</li>
									<% if user_signed_in? && current_user&.is_employee?(current_user)%>
									<li><!-- ADMIN -->
										<a id="admin-nav" href="/admin">
											ADMIN
										</a>
									</li>
									<li class="dropdown">
										<a class="dropdown-toggle" id="services-nav" >
										  INTERVENTION
											</a>
										<ul class="dropdown-menu">
										  <li><a href="/interventions/new">NEW INTERVENTION</a></li>
										  <li><a href="/interventions">ALL INTERVENTION</a></li>
										</ul>
									</li>
									<% end %>
									<% if user_signed_in? %> 
                                    <li><!-- USERS logout -->
                                    <%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %>
                                    </li>
                                    <% else %>
                                    <li><!-- USERS login -->
                                     <%= link_to "LOGIN", new_user_session_path %>
                                    </li>
                                    <% end %>
								</ul>

							</nav>
						</div>

					</div>
				</header>
				<!-- /Top Nav -->
			</div>

<div id="ctnAllIntervention">

<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  
  <thead>
    <tr>
      <th>Author_id</th>
      <th>Customer_id</th>
      <th>Building_id</th>
      <th>Battery_id</th>
      <th>Column_id</th>
      <th>Elevator_id</th>
      <th>Employee_id</th>
      <th>Start_date</th>
      <th>End_date</th>
      <th>Result</th>
      <th>Report</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.author_id %></td>
        <td><%= intervention.customer_id %></td>
        <td><%= intervention.building_id %></td>
        <td><%= intervention.battery_id %></td>
        <td><%= intervention.column_id %></td>
        <td><%= intervention.elevator_id %></td>
        <td><%= intervention.employee_id %></td>
        <td><%= intervention.start_date %></td>
        <td><%= intervention.end_date %></td>
        <td><%= intervention.result %></td>
        <td><%= intervention.report %></td>
        <td><%= intervention.status %></td>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path, {id: 'backbutton'} %>
</div>

<footer id="footer" style="margin-top:50px">
				<div class="container" >


					<div class="row">

						<!-- col #1 -->
						<div class="col-md-8">

							<h3 class="letter-spacing-1">WHY US?</h3>

							<!-- Small Description -->
							<p>
							We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have.

							</p>
							<h2>(418) 555-1234</h2>
						</div>
						<!-- /col #1 -->

						
					</div>


				</div>

				<div class="copyright">
					<div class="container">
						<ul class="float-right m-0 list-inline mobile-block">
							<li>Terms &amp; Conditions</li>
							<li>&bull;</li>
							<li>Privacy</li>
						</ul>
						&copy; All Rights Reserved, Rocket Elevators
					</div>
				</div>

			</footer>

app/views/interventions/new.html.erb
<div id="header" class="navbar-toggleable-md sticky clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">

						<!-- Mobile Menu Button -->
						<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars"></i>
						</button>

						<!-- Logo -->
						<a class="logo float-left scrollTo" href="#top" style="background-color: #FFFFFF">
							<img src="<%= asset_path('R2.png') %>" alt="" />
						</a>

						<!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
						<div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
							<nav class="nav-main">

								<!-- 
									
									
									Add .external for an external link!
								-->
								<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
									<li class="active"><!-- HOME -->
										<a id="home-nav" href="/index">
											HOME
										</a>
									</li>
									<li><!-- SERVICES -->
										<li class="dropdown">
										<a class="dropdown-toggle" id="services-nav" href="/index#services">
										  SERVICES
											</a>
										<ul class="dropdown-menu">
										  <li><a href="residential">Residential</a></li>
										  <li><a href="commercial">Commercial</a></li>
										</ul>
									</li>
									</li>
									<li><!-- PORTFOLIO -->
										<a id="portfolio-nav" href="/index#PORTFOLIO">
											PORTFOLIO
										</a>
									</li>
									<li><!-- NEWS -->
										<a id="news-nav" href="/index#news">
											NEWS
										</a>
									</li>

									<li><!-- CLIENTS -->
										<a id="clients-nav" href="/index#clients">
											CLIENTS
										</a>
									</li>

									<li><!-- CONTACT -->
										<a id="contact-nav" href="/index#contact">
											CONTACT
										</a>
									</li>
									<% if user_signed_in? && current_user&.is_employee?(current_user)%>
									<li><!-- ADMIN -->
										<a id="admin-nav" href="/admin">
											ADMIN
										</a>
									</li>
									<li class="dropdown">
										<a class="dropdown-toggle" id="services-nav" >
										  INTERVENTION
											</a>
										<ul class="dropdown-menu">
										  <li><a href="/interventions/new">NEW INTERVENTION</a></li>
										  <li><a href="/interventions">ALL INTERVENTION</a></li>
										</ul>
									</li>
									<% end %>
									<% if user_signed_in? %> 
                                    <li><!-- USERS logout -->
                                    <%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %>
                                    </li>
                                    <% else %>
                                    <li><!-- USERS login -->
                                     <%= link_to "LOGIN", new_user_session_path %>
                                    </li>
                                    <% end %>
								</ul>

							</nav>
						</div>

					</div>
				</header>
				<!-- /Top Nav -->
			</div>


<h1 class="d-flex justify-content-center align-items-center" style="margin-top:50px">New Intervention</h1>
<div style="background-color: #c7c7c7;width:50%;margin-left:25%;border-radius:10px;padding:20px;box-shadow: 5px 5px 10px grey;background:linear-gradient(14deg, rgba(223,223,223,1) 0%, rgba(37,135,186,1) 100%);">
    <%= render 'form', intervention: @intervention %>
    <%= link_to 'Back', interventions_path, {id: 'backbutton'} %>
</div>


<footer id="footer" style="margin-top:50px">
				<div class="container" >


					<div class="row">

						<!-- col #1 -->
						<div class="col-md-8">

							<h3 class="letter-spacing-1">WHY US?</h3>

							<!-- Small Description -->
							<p>
							We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have.

							</p>
							<h2>(418) 555-1234</h2>
						</div>
						<!-- /col #1 -->

						
					</div>


				</div>

				<div class="copyright">
					<div class="container">
						<ul class="float-right m-0 list-inline mobile-block">
							<li>Terms &amp; Conditions</li>
							<li>&bull;</li>
							<li>Privacy</li>
						</ul>
						&copy; All Rights Reserved, Rocket Elevators
					</div>
				</div>

			</footer>

app/views/interventions/show.html.erb
<div id="header" class="navbar-toggleable-md sticky clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">

						<!-- Mobile Menu Button -->
						<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars"></i>
						</button>

						<!-- Logo -->
						<a class="logo float-left scrollTo" href="#top" style="background-color: #FFFFFF">
							<img src="<%= asset_path('R2.png') %>" alt="" />
						</a>

						<!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
						<div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
							<nav class="nav-main">

								<!-- 
									
									
									Add .external for an external link!
								-->
								<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
									<li class="active"><!-- HOME -->
										<a id="home-nav" href="/index">
											HOME
										</a>
									</li>
									<li><!-- SERVICES -->
										<li class="dropdown">
										<a class="dropdown-toggle" id="services-nav" href="/index#services">
										  SERVICES
											</a>
										<ul class="dropdown-menu">
										  <li><a href="residential">Residential</a></li>
										  <li><a href="commercial">Commercial</a></li>
										</ul>
									</li>
									</li>
									<li><!-- PORTFOLIO -->
										<a id="portfolio-nav" href="/index#PORTFOLIO">
											PORTFOLIO
										</a>
									</li>
									<li><!-- NEWS -->
										<a id="news-nav" href="/index#news">
											NEWS
										</a>
									</li>

									<li><!-- CLIENTS -->
										<a id="clients-nav" href="/index#clients">
											CLIENTS
										</a>
									</li>

									<li><!-- CONTACT -->
										<a id="contact-nav" href="/index#contact">
											CONTACT
										</a>
									</li>
									<% if user_signed_in? && current_user&.is_employee?(current_user)%>
									<li><!-- ADMIN -->
										<a id="admin-nav" href="/admin">
											ADMIN
										</a>
									</li>
									<li class="dropdown">
										<a class="dropdown-toggle" id="services-nav">
										  INTERVENTION
											</a>
										<ul class="dropdown-menu">
										  <li><a href="/interventions/new">NEW INTERVENTION</a></li>
										  <li><a href="/interventions">ALL INTERVENTION</a></li>
										</ul>
									</li>
									<% end %>
									<% if user_signed_in? %> 
                                    <li><!-- USERS logout -->
                                    <%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %>
                                    </li>
                                    <% else %>
                                    <li><!-- USERS login -->
                                     <%= link_to "LOGIN", new_user_session_path %>
                                    </li>
                                    <% end %>
								</ul>

							</nav>
						</div>

					</div>
				</header>
				<!-- /Top Nav -->
			</div>



<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center">
  <p style="margin:10px 20px">
    <strong>Author:</strong>
    <%= @intervention.author_id %>
  </p>

  <p style="margin:10px 20px">
    <strong>Customerid:</strong>
    <%= @intervention.customer_id %>
  </p>

  <p style="margin:10px 20px">
    <strong>Buildingid:</strong>
    <%= @intervention.building_id %>
  </p>
</div>


<div class="d-flex justify-content-center">
  <p style="margin:10px 20px">
    <strong>Batteryid:</strong>
    <%= @intervention.battery_id %>
  </p>

  <p style="margin:10px 20px">
    <strong>Columnid:</strong>
    <%= @intervention.column_id %>
  </p>

  <p style="margin:10px 20px">
    <strong>Elevatorid:</strong>
    <%= @intervention.elevator_id %>
  </p>
</div>

<div class="d-flex justify-content-center">
  <p style="margin:10px 20px">
    <strong>Employeeid:</strong>
    <%= @intervention.employee_id %>
  </p>

  <p style="margin:10px 20px">
    <strong>Startdate:</strong>
    <%= @intervention.start_date %>
  </p>

  <p style="margin:10px 20px">
    <strong>Enddate:</strong>
    <%= @intervention.end_date %>
  </p>
</div>

<div class="d-flex justify-content-center">
  <p style="margin:10px 20px">
    <strong>Result:</strong>
    <%= @intervention.result %>
  </p>

  <p style="margin:10px 20px">
    <strong>Report:</strong>
    <%= @intervention.report %>
  </p>

  <p style="margin:10px 20px">
    <strong>Status:</strong>
    <%= @intervention.status %>
  </p>
</div>


<%= link_to 'Edit', edit_intervention_path(@intervention), {id: 'backbutton'} %> |
<%= link_to 'Back', interventions_path, {id: 'backbutton'} %>



<footer id="footer" style="margin-top:50px">
				<div class="container" >


					<div class="row">

						<!-- col #1 -->
						<div class="col-md-8">

							<h3 class="letter-spacing-1">WHY US?</h3>

							<!-- Small Description -->
							<p>
							We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have.

							</p>
							<h2>(418) 555-1234</h2>
						</div>
						<!-- /col #1 -->

						
					</div>


				</div>

				<div class="copyright">
					<div class="container">
						<ul class="float-right m-0 list-inline mobile-block">
							<li>Terms &amp; Conditions</li>
							<li>&bull;</li>
							<li>Privacy</li>
						</ul>
						&copy; All Rights Reserved, Rocket Elevators
					</div>
				</div>

			</footer>